export default {
  signIn: '/api/account/signIn',
  getAccountInfo: '/api/account/info',
  getBindWeChatQRCode: '/api/account/getBindWeChatQRCode',
  getOptions: '/api/base/options',
  form: '/api/form',
  company: '/api/company',
  menu: '/api/menu',
  view: '/api/view',
  data: '/api/data',
  task: '/api/task',
  platform: '/api/platform',
  shop: '/api/shop',
  ds: {
    student: '/api/ds/student',
    getStudentListBySubject: '/api/ds/student/getListBySubject',
    class: '/api/ds/class',
    school: '/api/ds/school',
    pay: '/api/ds/pay',
    exam: '/api/ds/exam/batch',
  },
};
