name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.x'

      - name: Build Project
        run: yarn && yarn run build

      - name: Deploy to Server
        uses: hengkx/ssh-deploy@v1.0.1
        with:
          USERNAME: ${{ secrets.DEPLOY_USER }}
          PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          HOST: ${{ secrets.DEPLOY_HOST }}
          SOURCE: 'build'
          TARGET: '/root/privacy/mobile-web'
